### ISSUE TITLE
nginx position in compose

### ISSUE THREAD

**Issue by oneofthemany** [metrico/iox-community#2]
you need to have nginx after iox in the compose file to work correctly

otherwise you have to manually start nginx_container

:)

**Comment by lmangani** [comment]
Hello @oneofthemany In my test setup this is not an issue.  Could you be more specific or submit a PR? 
We can simply add  `depends_on` logic if required by the flow on slower starting systems.

**Comment by oneofthemany** [comment]
Here is my process of determining that nginx needs to be below iox in your compose file:
```
[root@fedora influx_iox]#podman ps -a
2bca62787587  docker.io/library/nginx:latest                 nginx -g daemon o...  40 seconds ago  Exited (1) 40 seconds ago            0.0.0.0:9086->8086/tcp                          nginx_container
4c91d837eb77  ghcr.io/metrico/iox-musl:latest                /influxdb_iox run     39 seconds ago  Up 39 seconds                        0.0.0.0:8080->8080/tcp, 0.0.0.0:8082->8082/tcp  iox
fc23893290b5  docker.io/grafana/grafana:latest                                     38 seconds ago  Up 38 seconds                        0.0.0.0:3000->3000/tcp                          influx_iox_grafana_1

```
As you can see nginx exited, now to the logs:

```
[root@fedora influx_iox]# podman logs nginx_container 
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/07/21 13:55:30 [emerg] 1#1: host not found in upstream "iox" in /etc/nginx/nginx.conf:8
nginx: [emerg] host not found in upstream "iox" in /etc/nginx/nginx.conf:8
```
As you can see nginx cant find iox in the upstream as nginx is up before iox and therefore exits.

by changing the compose file to being as follows:

```
version: '2.1'

volumes:
  iox_data: {}
  postgres_data: {}
  grafana_data: {}

services:
  iox:
    privileged: true
    security_opt:
      - label=disable
    image: ghcr.io/metrico/iox-musl:latest
    container_name: iox
    volumes:
      - ./data:/data
    environment:
      - INFLUXDB_IOX_OBJECT_STORE=file
      - INFLUXDB_IOX_DB_DIR=/data
      - INFLUXDB_IOX_BUCKET=iox
      - INFLUXDB_IOX_CATALOG_DSN=sqlite:///data/catalog.sqlite
      - INFLUXDB_IOX_ROUTER_HTTP_BIND_ADDR=iox:8080
      - INFLUXDB_IOX_ROUTER_GRPC_BIND_ADDR=iox:8081
      - INFLUXDB_IOX_QUERIER_GRPC_BIND_ADDR=iox:8082
      - INFLUXDB_IOX_INGESTER_GRPC_BIND_ADDR=iox:8083
      - INFLUXDB_IOX_COMPACTOR_GRPC_BIND_ADDR=iox:8084
      - INFLUXDB_IOX_PERSIST_HOT_PARTITION_COST=0
      - LOG_FILTER=error
    restart: unless-stopped
    expose:
      - 8080
      - 8081
      - 8082
      - 8083
      - 8084
    ports:
      - 8080:8080
      - 8082:8082

  nginx:
    privileged: true
    security_opt:
      - label=disable
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./iox-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9086:8086
    expose:
      - 9086

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000

```
It allows iox to be up before compose brings up nginx and thus removing the need to do:

```
[root@fedora influx_iox]# podman start nginx_container 
nginx_container
[root@fedora influx_iox]# podman logs nginx_container 
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/07/21 14:00:25 [emerg] 1#1: host not found in upstream "iox" in /etc/nginx/nginx.conf:8
nginx: [emerg] host not found in upstream "iox" in /etc/nginx/nginx.conf:8
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
192.168.1.2 - - [21/Jul/2023:14:00:52 +0000] "POST /api/v2/write?org=hawthorn&bucket=fluent_bit&precision=ns HTTP/1.1" 204 0 "-" "Fluent-Bit"

```

:)
