### ISSUE TITLE
Traefik Bad Gateway Error

### ISSUE THREAD

**Issue by dblock247** [metrico/iox-community#3]
I am trying to run influxdb 3 iox behind traefik proxy. When trying to access the link I get a bad gateway request. Here is my docker compose file.

``` yaml
version: "3.8"
name: iox
services:

  iox:
    container_name: iox
    image: ghcr.io/metrico/iox-musl:latest
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "8080:8080"
      - "8082:8082"
    volumes:
      - /opt/docker/iox/data:/data
    environment:
      - INFLUXDB_IOX_OBJECT_STORE=file
      - INFLUXDB_IOX_DB_DIR=/data
      - INFLUXDB_IOX_BUCKET=iox
      - INFLUXDB_IOX_CATALOG_DSN=sqlite:///data/catalog.sqlite
      - INFLUXDB_IOX_ROUTER_HTTP_BIND_ADDR=iox:8080
      - INFLUXDB_IOX_ROUTER_GRPC_BIND_ADDR=iox:8081
      - INFLUXDB_IOX_QUERIER_GRPC_BIND_ADDR=iox:8082
      - INFLUXDB_IOX_INGESTER_GRPC_BIND_ADDR=iox:8083
      - INFLUXDB_IOX_COMPACTOR_GRPC_BIND_ADDR=iox:8084
      - INFLUXDB_IOX_PERSIST_HOT_PARTITION_COST=0
      - LOG_FILTER=debug
    expose:
      - 8080
      - 8081
      - 8082
      - 8083
      - 8084
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.iox.entrypoints=https
      - traefik.http.routers.iox.rule=Host(`domain.dev`)
      - traefik.http.routers.iox.service=iox
      - traefik.http.services.iox.loadbalancer.server.port=8086
      
networks:
  proxy:
    external: true
```
